from django.urls import path, include
from . import views
urlpatterns = [
    path('',views.Home,name='Home'),
    path('Orders',views.Orders,name='Orders'),
    path('More',views.More,name='More'),
    path('Mobile',views.Mobile,name='Mobile'),
    path('Laptop',views.Laptop,name='Laptop'),
    path('Accessories',views.Accessories,name='Accessories'),
    path('Clothes',views.Clothes,name='Clothes'),
    path('Grocery',views.Grocery,name='Grocery'),
    path('Oa',views.Oa,name='Oa'),
    path('Sr',views.Sr,name='Sr'),
    path('View',views.View,name='View'),
    path('Cart',views.Cart,name='Cart'),
    path('AddProduct',views.AddProduct,name='AddProduct'),
    path('Product',views.Product,name='Product'),
    path('AddUser',views.AddUser,name='AddUser'),
    path('User',views.User,name='User'),
    path('Login',views.Login,name='Login'),
    path('FogPas',views.FogPas,name='FogPas'),
    path('DelUsr',views.DelUsr,name='DelUsr'),
    path('UpPrd',views.UpPrd,name='UpPrd'),
    path('DelPrd',views.DelPrd,name='DelPrd'),
    path('LGout',views.LGout,name='LGout'),
    path('Remove',views.Remove,name='Remove'),
    path('CheckOut',views.CheckOut,name='CheckOut'),
    path('Deliver',views.Deliver,name='Deliver'),
    path('Signin',views.Signin,name='Signin'),
    path('Validation',views.Validation,name='Validation'),
]
